name: Extract Zip

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract MobileGlues.zip
        run: |
          unzip -o Natives/external/MobileGlues.zip -d Natives/external/MobileGlues
          
      - name: Verify extraction (Opsional - untuk mengecek isi folder)
        run: |
          ls -la Natives/external/MobileGlues
