name: Extract Zip

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract MobileGlues.zip
        run: |
          unzip -o Natives/external/MobileGlues.zip -d Natives/external/MobileGlues
          
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add Natives/external/MobileGlues/
          
          git diff --quiet && git diff --staged --quiet || (git commit -m "Extract MobileGlues.zip [skip ci]" && git push)
